<a href="https://colab.research.google.com/github/RAHUL20012807/python-data-science/blob/main/Pyds_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 From the above array, retrieve the values([[3,4],[5,6]]) using indexing

In [ ]:
 import numpy as np

In [ ]:
 a=np.array([1,2,3,4,5,6,7,8])

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a1=a[2:4]
a1

array([3, 4])

In [ ]:
a2=a[4:6]
a2

array([5, 6])

In [ ]:
arr=np.concatenate(([a1],[a2]))
arr

array([[3, 4],
       [5, 6]])